import "./globals.css";
import Head from "next/head";


export const metadata = {
  title: "Dimas Deo Rezkidyo",
  description: "Generated by create next app",
  icons: {
    icon: '/images/icon.svg'
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="font-roca "
      >
        {children}
      </body>
    </html>
  );
}
